
SCENARIO_DIR = "/workdir/src/mrta_main/scenarios"

S_MIN = 0.01
N_ITER = 300
POP_SIZE = 10
MUTA_PROB = 0.7
CROSSOVER_PROB = 0.7
CHECK_DEPS = True
CHECK_PREREQS = True
CHECK_PERF_IDX = True
K_D = 1
MATPLOT_SIZE = 7